server:
  port: 8888
  
spring:
  application:
    name: blog-admin
  profiles:
    active: dev
  data:
    mongodb:
      host: 192.168.155.128
      uri: mongodb://192.168.155.128:27017/blog-admin
      port: 27017
      database: blog-admin
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher