server:
  port: 8888
  servlet:
    context-path: /api
  # SSL config see  https://github.com/helloworlde/SpringBootCollection/tree/master/SpringBoot-Https
  # 生成证书 keytool -genkeypair -alias simple -keyalg RSA -keysize 2048 -storetype PKCS12 -keystore simple.p12 -validity 10
#  ssl:
#    key-store-type: PKCS12
#    key-store: classpath:simple.p12
#    key-store-password: 123456
#    key-alias: simple
#    enabled: true

spring:
  datasource:
    url: jdbc:mysql://101.43.38.61:30589/blog?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "root"
    password: "123456"
  application:
    name: blog-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848