apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
  labels:
    app: blog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: ccr.ccs.tencentyun.com/simple-blog/blog-service:v2
          ports:
            - containerPort: 8888
              hostPort: 8888
      imagePullSecrets:
        - name: txRepoSecret

---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  labels:
    app: blog-service
spec:
  ports:
    - port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: blog-service